os: linux
language: cpp

compiler:
  - gcc

before_script:
  - apt-get update -y && \
    apt-get install -y \
    --no-install-recommends apt-utils \
    build-essential \
    automake \
    bison \
    curl \
    coreutils \
    file \
    gettext \
    make \
    openssl \
    libssl-dev \
    libgcrypt11-dev \
    libcurl4-openssl-dev \
    zlib1g \
    zlib1g-dev \
    expat \
    libexpat1-dev \
    patch \
    perl \
    unzip \
    wget \
    yasm \
    lftp \
    zip \
    dos2unix \
    ghostscript
  #
  # Install opencv and opencv_contrib
  #
  cd /tmp && \
    git clone https://github.com/opencv/opencv.git && \
    cd opencv && \
    git checkout 3.4.3 && \
    cd .. && \
    git clone https://github.com/opencv/opencv_contrib.git && \
    cd opencv_contrib && \
    git checkout 3.4.3 && \
    cd ../opencv && \
    mkdir build && cd build && \
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D BUILD_SHARED_LIBS=ON \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules .. && \
    make -j"$(nproc --all)" && \
    make install

script:
- mkdir build
- cd build
- cmake ..
- cmake --build .
